### ISSUE TITLE
Folded AFS

### ISSUE THREAD

**Issue by andersgs** [kern-lab/im_clam#2]
Hello.

I am wondering if tool would work with a folded AFS, when one does not know which is the ancestral allele?

Thank you.

Anders.

**Comment by andrewkern** [comment]
Hi- sorry this only works with the unfolded SFS currently

**Comment by andersgs** [comment]
Thank you. Is it robust to not knowing which is the ancestral allele? Could I randomly assign an allele at each locus as ancestral?

**Comment by andrewkern** [comment]
No it's not-- mispolarization of the SFS will really mess things up!
