### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by andersgs** [kern-lab/im_clam#3]
Hello.

The AFS input matrix is not a very standard input format for most population genomic software. Do you have any scripts that will take a standard input and generate the AFS input file?

Thank you.

Anders.

**Comment by andrewkern** [comment]
What is your standard input format? IM_CLAM just takes as input a matrix representing the joint SFS, a quite simple format. The frequency spectrum tools in the dadi library will do this for you if you don't want to write your own script.

**Comment by andersgs** [comment]
I guess there are several, but GenePop has been about for a long time and VCF is possibly another as we move into more genomic-sized data.

The input is quite simple. I agree. It would just be a good will nod to your users to supply an easy way to get from some raw data to the input format. I'll try `dadi`. If you accept PRs, I can add some instructions to the README depending on what I find.

Thank you.

**Comment by andrewkern** [comment]
Sure happy to accept PRs
